version: '3.9'

services:
    database-layer:
        image: mongo:latest
        container_name: mongo_devops
        environment:
            - PORT=27017
        ports:
            - 27017:27017
        # networks:
        #     - mydemo
        # provide your credentials here
            # - MONGO_INITDB_ROOT_USERNAME=root
            # - MONGO_INITDB_ROOT_PASSWORD=rootPassXXX
        # command: ["docker run --name mongo -d --rm --network mydemo "]
        volumes:
            - ./data:/data/db
    api:
        build: ./api
        depends_on:
        - database-layer
        environment:
            - PORT=3000
            - DB=mongo_devops
        ports:
            - 3000:3000
        depends_on: 
            - database-layer
    frontend:
        build: ./frontend
        depends_on:
        - api
        environment:
            - PORT=4200
        ports:
            - 4200:4200
        depends_on: 
            - database-layer
            - api

#docker run --rm -p 4200:4200 --name frontend frontend
#docker run --rm -p 3000:3000 --network mydemo --env DB=mongo --name api api
#docker run --name mongo -d --rm --network mydemo -v ${pwd}/data:/data/db -p 27017:27017 mongo:latest